---
title: "Complex in-built objects in R"
author: "Luciano Gabbanelli"
date: "2022-10-10"
output:
  html_document:
    toc: true
    toc_float: true
    collapse: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
---

## 1. Squares of maximum and minumums

```{r}

my.vec <- round(runif(25,1,50)); my.vec

if (max(my.vec) > (2*min(my.vec))) {
  print(min(my.vec)^2)
} else if (max(my.vec) < (5*min(my.vec))){
  print(max(my.vec)^2)
} else {
    print(sort(my.vec, decreasing=TRUE))
  }

```


## 2. Random matrices

```{r}
N = 4
random_matrix <- round(matrix(runif(N*N,1,N),nrow=N)); random_matrix
my.vector <- vector(mode = "integer", length = N); my.vector

for (i in seq_along(1:N)){
  my.vector[i] <- sum(random_matrix==i)
  print(paste("The number ", i, "appears ", my.vector[i], "times."))
}

my.vector
print(random_matrix)

```




## 3. Salary

```{r}

salary <- as.numeric(readline("Introduce a salary: "))

if (salary > 1750){
  salary_new <- salary*1.10
  cat("The new salary is: ", salary)
} else {
  salary <- salary*1.15
  cat("The new salary is: ", salary)
}

```

# 4. Divisible by 3 and 5

```{r}
my.vec <- c(1000:1)

div.vec <- c()
index <- 1

for (n in my.vec){
  if ( (n %% 3 == 0) & (n %% 5 == 0) & (n %% 7 == 0) ){
    if (n == 525){next}
    div.vec[index] <- n
    index <- index + 1
  }
}

div.vec
```

## 5. Value times index

```{r}

x <- sample.int(100, 10)
x
typeof(x)
new.vec <- c()
index <- 1
while (index <= length(x)){
  new.vec[index] <- x[index] * index
  index <- index + 1 
}

new.vec

```


## 6. Normal distribution with modulus less (or equal) than one

```{r}


my.list <- list()

repeat {
  x <- rnorm(1)
  if (abs(x) > 1){
    break
  }
  my.list <- append(my.list,x)
}

my.list

```



## 8. Clear of NAs

```{r}

my.df <- data.frame(
  "students" = c("Jose", "María", "Ana", "Javier", "Natalia", "Jorge", "Jose","Elis"),
  "age" = c(30, NA, NA, 25, 46, 14,NA,38),
  "working" = c(T,F,T,NA,F,T,NA,F))

my.df


reeplace.nas <- function(df.entry, rep.v.int, rep.v.bool){
  
  for (c in 1:ncol(df.entry)){

    for (r in 1:length(df.entry[[c]])){
      
      print((df.entry[[c]][r]))
      if (is.na(df.entry[[c]][r]) == T) {
        if (typeof(df.entry[[c]]) == "double"){
          df.entry[[c]][r] <- rep.v.int  
        } else {
          df.entry[[c]][r] <- rep.v.bool  
        }
      }
    }
  }
  return (df.entry)
}


df.clean <- reeplace.nas(df.entry = my.df, rep.v.int = median(my.df$age, na.rm=TRUE), rep.v.bool = T)

df.clean

class(df.clean[1])

df.clean[1] <- unlist(lapply(df.clean[1],toupper))

df.clean
df.clean[2]

length(df.clean[[2]])

tapply(df.clean[[2]], df.clean[[3]], mean)


```


## 9. Armstrong number

```{r}

armstrong <- function(){
  num_str = readline(prompt="Enter a number: ")
  num_list = unlist(strsplit(num_str, split=""))
  sum = 0
  for (digit in num_list){
    sum <- sum + as.integer(digit)^length(num_list)
  }
  if(as.integer(num_str) == sum) {
    return(paste(num_str, "is an Armstrong number"))
    } else {
    return(paste(num_str, "is not an Armstrong number"))
    }
}

armstrong()
```